# Clock
#set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports clk_i]
#create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk_i]

# Button
#set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS33} [get_ports {btn_i[0]}]
#set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports {btn_i[1]}]

# LEDs
#set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports {led_o[0]}]
#set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports {led_o[1]}]

#set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS33} [get_ports {ar_d[0]}]
#set_property -dict {PACKAGE_PIN B6  IOSTANDARD LVCMOS33} [get_ports {ar_d[1]}]
#set_property -dict {PACKAGE_PIN A5  IOSTANDARD LVCMOS33} [get_ports {ar_d[2]}]
#set_property -dict {PACKAGE_PIN B5  IOSTANDARD LVCMOS33} [get_ports {ar_d[3]}]
#set_property -dict {PACKAGE_PIN A4  IOSTANDARD LVCMOS33} [get_ports {ar_d[4]}]
#set_property -dict {PACKAGE_PIN A3  IOSTANDARD LVCMOS33} [get_ports {ar_d[5]}]
#set_property -dict {PACKAGE_PIN B3  IOSTANDARD LVCMOS33} [get_ports {ar_d[6]}]
#set_property -dict {PACKAGE_PIN A2  IOSTANDARD LVCMOS33} [get_ports {ar_d[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {gport_a[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gport_b[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gport_c[*]}]

set_property PACKAGE_PIN N14 [get_ports {gport_a[0]}]
set_property PACKAGE_PIN M14 [get_ports {gport_a[1]}]
set_property PACKAGE_PIN C4  [get_ports {gport_a[2]}]
set_property PACKAGE_PIN B13 [get_ports {gport_a[3]}]
set_property PACKAGE_PIN N10 [get_ports {gport_a[4]}]
set_property PACKAGE_PIN M10 [get_ports {gport_a[5]}]
set_property PACKAGE_PIN B14 [get_ports {gport_a[6]}]
set_property PACKAGE_PIN D3  [get_ports {gport_a[7]}]
set_property PACKAGE_PIN P5  [get_ports {gport_a[8]}]
set_property PACKAGE_PIN E11 [get_ports {gport_a[9]}]
set_property PACKAGE_PIN L14 [get_ports {gport_a[10]}]
set_property PACKAGE_PIN P2  [get_ports {gport_a[11]}]
set_property PACKAGE_PIN D13 [get_ports {gport_a[12]}]
set_property PACKAGE_PIN J13 [get_ports {gport_a[13]}]
set_property PACKAGE_PIN J1  [get_ports {gport_a[14]}]
set_property PACKAGE_PIN A13 [get_ports {gport_a[15]}]
set_property PACKAGE_PIN A12 [get_ports {gport_a[16]}]
set_property PACKAGE_PIN C12 [get_ports {gport_a[17]}]
set_property PACKAGE_PIN A10 [get_ports {gport_a[18]}]
set_property PACKAGE_PIN B6  [get_ports {gport_a[19]}]
set_property PACKAGE_PIN A5  [get_ports {gport_a[20]}]
set_property PACKAGE_PIN B5  [get_ports {gport_a[21]}]
set_property PACKAGE_PIN A4  [get_ports {gport_a[22]}]
set_property PACKAGE_PIN A3  [get_ports {gport_a[23]}]
set_property PACKAGE_PIN B3  [get_ports {gport_a[24]}]
set_property PACKAGE_PIN B1  [get_ports {gport_a[25]}]
set_property PACKAGE_PIN H1  [get_ports {gport_a[26]}]
set_property PACKAGE_PIN H2  [get_ports {gport_a[27]}]
set_property PACKAGE_PIN J14 [get_ports {gport_a[28]}]
set_property PACKAGE_PIN L12 [get_ports {gport_a[29]}]
set_property PACKAGE_PIN L13 [get_ports {gport_a[30]}]
set_property PACKAGE_PIN H14 [get_ports {gport_a[31]}]

set_property PACKAGE_PIN M13 [get_ports {gport_b[0]}]
set_property PACKAGE_PIN P13 [get_ports {gport_b[1]}]
set_property PACKAGE_PIN P12 [get_ports {gport_b[2]}]
set_property PACKAGE_PIN M2  [get_ports {gport_b[3]}]
set_property PACKAGE_PIN L2  [get_ports {gport_b[4]}]
set_property PACKAGE_PIN L3  [get_ports {gport_b[5]}]
set_property PACKAGE_PIN K3  [get_ports {gport_b[6]}]
set_property PACKAGE_PIN C3  [get_ports {gport_b[7]}]
set_property PACKAGE_PIN M4  [get_ports {gport_b[8]}]
set_property PACKAGE_PIN D14 [get_ports {gport_b[9]}]
set_property PACKAGE_PIN J4  [get_ports {gport_b[10]}]
set_property PACKAGE_PIN C5  [get_ports {gport_b[11]}]
set_property PACKAGE_PIN J3  [get_ports {gport_b[12]}]
set_property PACKAGE_PIN J2  [get_ports {gport_b[13]}]
set_property PACKAGE_PIN D12 [get_ports {gport_b[14]}]
set_property PACKAGE_PIN E12 [get_ports {gport_b[15]}]
set_property PACKAGE_PIN F12 [get_ports {gport_b[16]}]
set_property PACKAGE_PIN C11 [get_ports {gport_b[17]}]
set_property PACKAGE_PIN H11 [get_ports {gport_b[18]}]
set_property PACKAGE_PIN H12 [get_ports {gport_b[19]}]
set_property PACKAGE_PIN P4  [get_ports {gport_b[20]}]
set_property PACKAGE_PIN P3  [get_ports {gport_b[21]}]
set_property PACKAGE_PIN C14 [get_ports {gport_b[22]}]
set_property PACKAGE_PIN B11 [get_ports {gport_b[23]}]
set_property PACKAGE_PIN K4  [get_ports {gport_b[24]}]
set_property PACKAGE_PIN H3  [get_ports {gport_b[25]}]
set_property PACKAGE_PIN N4  [get_ports {gport_b[26]}]
set_property PACKAGE_PIN M3  [get_ports {gport_b[27]}]
set_property PACKAGE_PIN A2  [get_ports {gport_b[28]}]
set_property PACKAGE_PIN B2  [get_ports {gport_b[29]}]

set_property PACKAGE_PIN N1  [get_ports {gport_c[0]}]
set_property PACKAGE_PIN L1  [get_ports {gport_c[1]}]